package com.demo.common.model;

import com.demo.common.model.base.BaseReply;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Reply extends BaseReply<Reply> {
	public static final Reply dao = new Reply();
}
